## Importing the libraries

In [1]:
import pandas as pd

## Creating a reference for the skill requirements

In [2]:
web = set([i.strip() for i in 'HTML, CSS, Bootstrap, AJAX, JavaScript, PHP, MySQL, REST API, Deployment, Git, Python, Linux, JSON, JWT'.split(',')])

In [3]:
full = set([i.strip() for i in 'HTML, CSS, MongoDB, Express, ReactJS, Node.js, ES6, Redux, JavaScript, Deployment, Python, Linux, JSON, JWT'.split(',')])

In [4]:
ml = set([i.strip() for i in 'Python, TensorFlow, PyTorch, NumPy, PyPI, Sci-kit learn, Statistical Modelling, Machine Learning, Deep Learning, SQL, JSON, Deployment, Flask'.split(',')])

## Importing the Dataset

In [5]:
df=pd.read_excel('sample_data_v4.xlsx')
df

,Application ID,Current City,Other skills,Institute,Degree,Stream,Current Year Of Graduation,Performance_PG,Performance_UG,Performance_12,Performance_10
0,MS0001,Pune,"Machine Learning, Python",Don Bosco Institute of Technology,Bachelor of Engineering (B.E),Mechanical Engineering,2018,NaN,8.13/10,NaN,NaN
1,MS0002,Pune,"Machine Learning, Python","PES MCOE, Pune",Bachelor of Engineering (B.E),Electronics and Telecommunication Engineering ...,2018,NaN,66.00/100,NaN,NaN
2,MS0003,Navi Mumbai,"Data Analytics, Data Science, Machine Learning...",Imarticus Learning,PG Diploma in Data Science,NaN,2020,NaN,7.00/10,NaN,NaN
3,MS0004,Bangalore,"Data Analytics, Algorithms, C Programming, Dat...",Dayananda Sagar Institutions,Bachelor of Technology (B.Tech),Information Technology,2022,NaN,NaN,86.80/86.80,10.00/10.00
4,MS0005,Mumbai,"Artifical Intelligence, Computer Vision, Deep ...",Pillai Hoc College Of Engineering And Technolo...,Bachelor of Engineering (B.E),Information Technology,2020,NaN,6.22/10,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2163,MS2164,Hyderabad,"Database Management System (DBMS), HTML, Pytho...","KIIT University, Bhubaneshwar",Bachelor of Technology (B.Tech),Computer Science & Engineering,2020,NaN,75.00/100,NaN,NaN
2164,MS2165,Bangalore,"CSS, Cloud Computing, HTML, PHP, Python, Andro...",L. N. C . T. Jabalpur,Master of Computer Applications (MCA),Computer Application,2020,7.78/10,6.80/10,NaN,NaN
2165,MS2166,Nagpur,"CSS, HTML, JavaScript, Python",Vellore Institute of Technology,Bachelor of Engineering (B.E),Electronics and Telecommunication Engineering ...,2020,NaN,6.10/10,62.62/62.62,NaN
2166,MS2167,Kanpur,"Android, C Programming, C++ Programming, Pytho...",Kakatiya Institute of Technology and Science,Bachelor of Technology (B.Tech),Computer Science & Engineering,2020,NaN,6.50/10,62.50/62.50,76.50/76.50
2167,MS2168,Durgapur,"C Programming, C++ Programming, JavaScript, CS...",National Institute Of Electronics & Informatio...,Master of Computer Applications (MCA),Computer Application,2020,6.40/10,63.06/100,64.00/64.00,64.60/64.60

## Editing for deployment and git

In [6]:
# The required skills AWS/Heroku/Google Cloud Computing are all clubbed into "Deployment" and Git SVN and Github are clubbed into "Git" because only one othose skills are enough and the company doesn't require all of the skills in the candidate. 
# But it is again restored to the original skills at the end for correct display of output.
 

for x in range(0,5):
    for i in df['Other skills']:
        if type(i)==str:
            if 'Amazon Web Server (AWS)' in i:
                tx = i.replace('Amazon Web Server (AWS)', 'Deployment')
                df.replace(i, tx, inplace=True)
            if 'Amazon Web Services (AWS)' in i:
                tx = i.replace('Amazon Web Services (AWS)', 'Deployment')
                df.replace(i, tx, inplace=True)
            if 'Google Cloud Computing' in i:
                tx = i.replace('Google Cloud Computing', 'Deployment')
                df.replace(i, tx, inplace=True)
            if 'Heroku' in i:
                tx = i.replace('Heroku', 'Deployment')
                df.replace(i, tx, inplace=True)
            if 'Git SVN' in i:
                tx = i.replace('Git SVN', 'Git')
                df.replace(i, tx, inplace=True)
            if 'GitHub' in i:
                tx = i.replace('GitHub', 'Git')
                df.replace(i, tx, inplace=True)

## Main Process of selection of candidate

In [7]:
# The process of selection of a candidate is purely based on hit and trial method. One candidate has to be selected each for 3 roles as an intern in the company.
# So the values pw_limit, pf_limit, pm_limit are set in order to get one candidate each for 3 different roles by hit and trial method. 
# The index, no of skills and probability of getting selected of the winners are stored in the lists winner_web, winner_fullstack, winner_ml. 
# The iteration process goes on for each and every entry in the dataset and the predicted role and skill gap are stored in the lists role_list & skillgap_list respectively. 


role_list=[]
skillgap_list=[]
winner_web, winner_fullstack, winner_ml=[],[],[]
pw_limit, pf_limit, pm_limit = 0.7, 0.55, 0.5
for x in range(0,len(df['Other skills'])):
    i= df['Other skills'].iloc[x]
    if type(i)==str:
        cand_skillset=set([l.strip() for l in i.split(',')])
        web_score,fullstack_score,ml_score=len(cand_skillset&web), len(cand_skillset&full), len(cand_skillset&ml)
        if (web_score/len(web)) > pw_limit:
            if(len(winner_web)==0):
                winner_web.extend([x, len(cand_skillset), web_score/len(web)])
                role_list.append('Web Developer')
                skillgap_list.append('NA')
            else:
                if len(cand_skillset)>winner_web[1]:
                    role_list[winner_web[0]]='NA'
                    s=''
                    for d in web:
                        if d not in cand_skillset:
                            s = s+d+','
                    skillgap_list[winner_web[0]]=s
                    winner_web[0],winner_web[1],winner_web[2]=x,len(cand_skillset),web_score/len(web)
                    role_list.append('Web Developer')
                    skillgap_list.append('NA')
                else:
                    role_list.append('NA')
                    s=''
                    for d in web:
                        if d not in cand_skillset:
                            s = s+d+','
                    skillgap_list.append(s)
                    
        elif (fullstack_score/len(full)) > pf_limit:
            if(len(winner_fullstack)==0):
                winner_fullstack.extend([x, len(cand_skillset), fullstack_score/len(full)])
                role_list.append('FullStack Developer')
                skillgap_list.append('NA')
            else:
                if len(cand_skillset)>winner_fullstack[1]:
                    role_list[winner_fullstack[0]]='NA'
                    s=''
                    for d in full:
                        if d not in cand_skillset:
                            s = s+d+','
                    skillgap_list[winner_fullstack[0]]=s
                    winner_fullstack[0],winner_fullstack[1],winner_fullstack[2]=x,len(cand_skillset),fullstack_score/len(full)
                    role_list.append('FullStack Developer')
                    skillgap_list.append('NA')
                else:
                    role_list.append('NA')
                    s=''
                    for d in full:
                        if d not in cand_skillset:
                            s = s+d+','
                    skillgap_list.append(s)
                    
                    
        elif (ml_score/len(ml)) > pm_limit:
            winner_ml.extend([x,len(cand_skillset), ml_score/len(ml)])
            role_list.append('ML Developer')
            skillgap_list.append('NA')
            
            
        else:
            role_list.append('NA')
            s=''
            if max(web_score, fullstack_score, ml_score)==web_score:
                for d in web:
                    if d not in cand_skillset:
                        s = s+d+','    
            elif max(web_score, fullstack_score, ml_score)==fullstack_score:
                for d in full:
                    if d not in cand_skillset:
                        s = s+d+','
            elif max(web_score, fullstack_score, ml_score)==ml_score:
                for d in ml:
                    if d not in cand_skillset:
                        s = s+d+','
            skillgap_list.append(s)
    else:
        role_list.append('NA')
        skillgap_list.append('NA')

df['Selected for'] = role_list
df['Lacking Skills'] = skillgap_list

In [8]:
print(winner_web,'\n',winner_fullstack,'\n',winner_ml)

[47, 48, 0.7857142857142857]
 [371, 35, 0.5714285714285714]
 [178, 24, 0.5384615384615384]

In [9]:
# Two separate columns are created "Selected For" and "Lacking Skills" for the role prediction of the selected candidate and skill gap respectively. 
# So the dataframe is displayed to observe the new columns.

df

,Application ID,Current City,Other skills,Institute,Degree,Stream,Current Year Of Graduation,Performance_PG,Performance_UG,Performance_12,Performance_10,Selected for,Lacking Skills
0,MS0001,Pune,"Machine Learning, Python",Don Bosco Institute of Technology,Bachelor of Engineering (B.E),Mechanical Engineering,2018,NaN,8.13/10,NaN,NaN,NA,"PyTorch,NumPy,SQL,TensorFlow,Deep Learning,Dep..."
1,MS0002,Pune,"Machine Learning, Python","PES MCOE, Pune",Bachelor of Engineering (B.E),Electronics and Telecommunication Engineering ...,2018,NaN,66.00/100,NaN,NaN,NA,"PyTorch,NumPy,SQL,TensorFlow,Deep Learning,Dep..."
2,MS0003,Navi Mumbai,"Data Analytics, Data Science, Machine Learning...",Imarticus Learning,PG Diploma in Data Science,NaN,2020,NaN,7.00/10,NaN,NaN,NA,"PyTorch,NumPy,SQL,TensorFlow,Deep Learning,Dep..."
3,MS0004,Bangalore,"Data Analytics, Algorithms, C Programming, Dat...",Dayananda Sagar Institutions,Bachelor of Technology (B.Tech),Information Technology,2022,NaN,NaN,86.80/86.80,10.00/10.00,NA,"PyTorch,NumPy,TensorFlow,Deployment,Flask,JSON..."
4,MS0005,Mumbai,"Artifical Intelligence, Computer Vision, Deep ...",Pillai Hoc College Of Engineering And Technolo...,Bachelor of Engineering (B.E),Information Technology,2020,NaN,6.22/10,NaN,NaN,NA,"PyTorch,NumPy,TensorFlow,Flask,JSON,Sci-kit le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2163,MS2164,Hyderabad,"Database Management System (DBMS), HTML, Pytho...","KIIT University, Bhubaneshwar",Bachelor of Technology (B.Tech),Computer Science & Engineering,2020,NaN,75.00/100,NaN,NaN,NA,"AJAX,JavaScript,Git,JWT,Bootstrap,Deployment,C..."
2164,MS2165,Bangalore,"CSS, Cloud Computing, HTML, PHP, Python, Andro...",L. N. C . T. Jabalpur,Master of Computer Applications (MCA),Computer Application,2020,7.78/10,6.80/10,NaN,NaN,NA,"AJAX,Git,JWT,Bootstrap,Deployment,JSON,REST AP..."
2165,MS2166,Nagpur,"CSS, HTML, JavaScript, Python",Vellore Institute of Technology,Bachelor of Engineering (B.E),Electronics and Telecommunication Engineering ...,2020,NaN,6.10/10,62.62/62.62,NaN,NA,"AJAX,Git,JWT,Bootstrap,Deployment,JSON,REST AP..."
2166,MS2167,Kanpur,"Android, C Programming, C++ Programming, Pytho...",Kakatiya Institute of Technology and Science,Bachelor of Technology (B.Tech),Computer Science & Engineering,2020,NaN,6.50/10,62.50/62.50,76.50/76.50,NA,"AJAX,JavaScript,Git,JWT,Bootstrap,Deployment,C..."
2167,MS2168,Durgapur,"C Programming, C++ Programming, JavaScript, CS...",National Institute Of Electronics & Informatio...,Master of Computer Applications (MCA),Computer Application,2020,6.40/10,63.06/100,64.00/64.00,64.60/64.60,NA,"AJAX,Git,JWT,Bootstrap,Deployment,JSON,REST AP..."

## User input

In [10]:
print('The choices for a role to work as an intern are as follows:\n')
print("NOTE : Please choose the desired role as per the choices listed below :\n ")
print('1. Web Developer\n')
print('2. FullStack Developer\n')
print('3. Machine Learning Developer\n')
role = int(input("Choose your desired role based on the choices and enter 1 for Web Developer, 2 for FullStack Developer and 3 for Machine Learning Developer : "))
if (role<1 or role>3):
    print("\nInvalid choice. Please choose the correct option among 1, 2, 3 as per the given list above\n")
    role = int(input("Choose your desired role based on the choices and enter 1 for Web Developer, 2 for FullStack Developer and 3 for Machine Learning Developer : "))
print("\nNOTE : Please try to mention as many skills as possible which match the skills given by you in the application for this internship for correct display of results...\n ")
skills = input("Enter your skills one by one using commas : ")
skill_set = list([i.strip() for i in skills.split(',')])

The choices for a role to work as an intern are as follows:

NOTE : Please choose the desired role as per the choices listed below :

1. Web Developer

2. FullStack Developer

3. Machine Learning Developer

Choose your desired role based on the choices and enter 1 for Web Developer, 2 for FullStack Developer and 3 for Machine Learning Developer : 5

Invalid choice. Please choose the correct option among 1, 2, 3 as per the given list above

Choose your desired role based on the choices and enter 1 for Web Developer, 2 for FullStack Developer and 3 for Machine Learning Developer : 2

NOTE : Please try to mention as many skills as possible which match the skills given by you in the application for this internship for correct display of results...

Enter your skills one by one using commas : AJAX, CSS, HTML, Bootstrap, C Programming, C++ Programming, JavaScript, Machine Learning, Node.js, Python, ReactJS, Redux

## Normalisation of the skillset provided by user

In [11]:
# It is the same process as done in the section "Editing for deployment and git" but here, it is done for processing the user input section only


for i in range(len(skill_set)):
    if skill_set[i]=='Amazon Web Server (AWS)' or skill_set[i]=='Amazon Web Serices (AWS)' or skill_set[i]=='Google Cloud Computing' or skill_set[i]=='Heroku' or skill_set[i]=='AWS' or skill_set[i]=='GCP':
        skill_set[i]='Deployment'
    elif skill_set[i]=='Git SVN' or skill_set[i]=='GitHub':
        skill_set[i]= 'Git'
skill_set=set(skill_set)

In [12]:
skill_set

{'AJAX',
 'Bootstrap',
 'C Programming',
 'C++ Programming',
 'CSS',
 'HTML',
 'JavaScript',
 'Machine Learning',
 'Node.js',
 'Python',
 'ReactJS',
 'Redux'}

##  Processing the user input and display of output

In [13]:
# This section of code only helps in the procssing of user input and displaying the output that the candidate is selected or not and if not selected then his/her skill gap based on his/her desired role and her skillset given in the user input. 
# The shortlisted candidates are already decided and this section of code is only for the info to be given to the user through output whether he/she is selected or not. 
# Here the w2,f2 and m2 are the scores for the skill set given in user input.


if len(skill_set)>0:
    if role == 1:
        w2=len(skill_set&web)
        if(w2/len(web))>=winner_web[2]:
            if len(skill_set)>=winner_web[1]:
                print('You are selected\n')
            else:
                print('You are not selected for your desired role. Thank you for your effort and keep working hard\n')
                s=''
                for d in web:
                    if d not in skill_set:
                        s = s+d+','
                if 'Deployment' in s:
                    s=s.replace('Deployment', 'AWS/GCP')
                print('Skill gap : ',s[:-1])
        else:
            print('You are not selected for your desired role. Thank you for your effort and keep working hard\n')
            s=''
            for d in web:
                if d not in skill_set:
                    s = s+d+','
            if 'Deployment' in s:
                    s=s.replace('Deployment', 'AWS/GCP')
            print('Skill gap : ',s[:-1])
            
    elif role == 2:
        f2=len(skill_set&full)
        if(f2/len(full))>=winner_fullstack[2]:
            if len(skill_set)>=winner_fullstack[1]:
                print('You are selected\n')
            else:
                print('You are not selected for your desired role. Thank you for your effort and keep working hard\n')
                s=''
                for d in full:
                    if d not in skill_set:
                        s = s+d+','
                if 'Deployment' in s:
                    s=s.replace('Deployment', 'AWS/GCP')
                print('Skill gap : ',s[:-1])
        else:
            print('You are not selected for your desired role. Thank you for your effort and keep working hard\n')
            s=''
            for d in full:
                if d not in skill_set:
                    s = s+d+','
            if 'Deployment' in s:
                    s=s.replace('Deployment', 'AWS/GCP')
            print('Skill gap : ',s[:-1])
    elif role == 3:
        m2=len(skill_set&ml)
        if(m2/len(full))>=winner_ml[2]:
            if len(skill_set)>=winner_ml[1]:
                print('You are selected\n')
            else:
                print('You are not selected for your desired role. Thank you for your effort and keep working hard\n')
                s=''
                for d in ml:
                    if d not in skill_set:
                        s = s+d+','
                if 'Deployment' in s:
                    s=s.replace('Deployment', 'AWS/GCP/Heroku')
                print('Skill gap : ',s[:-1])
        else:
            print('You are not selected for your desired role. Thank you for your effort and keep working hard\n')
            s=''
            for d in ml:
                if d not in skill_set:
                    s = s+d+','
            if 'Deployment' in s:
                    s=s.replace('Deployment', 'AWS/GCP/Heroku')
            print('Skill gap : ',s[:-1])

You are not selected for your desired role. Thank you for your effort and keep working hard

Skill gap :  Linux,AWS/GCP,JWT,ES6,MongoDB,JSON,Express